##Trabalho Computacional 2
### Métodos Numéricos 2021.1
Questão 1

In [ ]:
import numpy as np

In [ ]:
#Input de dados da matriz
ordem=int(input('Ordem da Matriz: '))
matriz=np.zeros((ordem, ordem), dtype='float')
for i in range(ordem):
  for j in range(ordem):
    print('Coeficiente [', i+1, '][', j+1,']')
    c=float(input('Input: ' ))
    matriz[i,j] = c
print (matriz)

Ordem da Matriz: 6
Coeficiente [ 1 ][ 1 ]
Input: 4
Coeficiente [ 1 ][ 2 ]
Input: -1
Coeficiente [ 1 ][ 3 ]
Input: 0
Coeficiente [ 1 ][ 4 ]
Input: -1
Coeficiente [ 1 ][ 5 ]
Input: 0
Coeficiente [ 1 ][ 6 ]
Input: 0
Coeficiente [ 2 ][ 1 ]
Input: -1
Coeficiente [ 2 ][ 2 ]
Input: 4
Coeficiente [ 2 ][ 3 ]
Input: -1
Coeficiente [ 2 ][ 4 ]
Input: 0
Coeficiente [ 2 ][ 5 ]
Input: -1
Coeficiente [ 2 ][ 6 ]
Input: 0
Coeficiente [ 3 ][ 1 ]
Input: 0
Coeficiente [ 3 ][ 2 ]
Input: -1
Coeficiente [ 3 ][ 3 ]
Input: 4
Coeficiente [ 3 ][ 4 ]
Input: 0
Coeficiente [ 3 ][ 5 ]
Input: 0
Coeficiente [ 3 ][ 6 ]
Input: -1
Coeficiente [ 4 ][ 1 ]
Input: -1
Coeficiente [ 4 ][ 2 ]
Input: 0
Coeficiente [ 4 ][ 3 ]
Input: 0
Coeficiente [ 4 ][ 4 ]
Input: 4
Coeficiente [ 4 ][ 5 ]
Input: -1
Coeficiente [ 4 ][ 6 ]
Input: 0
Coeficiente [ 5 ][ 1 ]
Input: 0
Coeficiente [ 5 ][ 2 ]
Input: -1
Coeficiente [ 5 ][ 3 ]
Input: 0
Coeficiente [ 5 ][ 4 ]
Input: -1
Coeficiente [ 5 ][ 5 ]
Input: 4
Coeficiente [ 5 ][ 6 ]
Input: -1
Coeficien

Utilizamos a função de gauss jordan para cálculo da matriz inversa

In [ ]:
def gauss_jordan_inversa(M):
  #copia a matriz
  A = np.copy(M)
  n = len(A)
  #cria uma matriz identidade
  I = np.identity(n)
  k=0
  while k<n:
    z=0
    #escolhe o pivo
    pivo=A[k,k]
    while z<n:
      #atualização dos elementos das matrizes dividindo pelo pivo escolhido A[k][k]
      A[k,z]=A[k,z]/pivo
      I[k,z]=I[k,z]/pivo
      z=z+1
    z=0
    while z<n:
      if z != k:
        #calcula o fator
        fator = (-1)*A[z,k]
        j=0
        while j<n:
          A[z,j] = fator*A[k,j]+A[z,j]
          I[z,j] = fator*I[k,j]+I[z,j]
          j=j+1
      z=z+1
    k=k+1
  return I

In [ ]:
inversa_matriz = gauss_jordan_inversa(matriz)

Resultado da matriz inversa calculada pelo método de gauss

In [ ]:
inversa_matriz

array([[0.29482402, 0.0931677 , 0.02815735, 0.08612836, 0.04968944,
        0.0194617 ],
       [0.0931677 , 0.32298137, 0.0931677 , 0.04968944, 0.10559006,
        0.04968944],
       [0.02815735, 0.0931677 , 0.29482402, 0.0194617 , 0.04968944,
        0.08612836],
       [0.08612836, 0.04968944, 0.0194617 , 0.29482402, 0.0931677 ,
        0.02815735],
       [0.04968944, 0.10559006, 0.04968944, 0.0931677 , 0.32298137,
        0.0931677 ],
       [0.0194617 , 0.04968944, 0.08612836, 0.02815735, 0.0931677 ,
        0.29482402]])

Para verificar se a matriz inversa está correta, multiplicamos a matriz original pela inversa e esperamos o resultado de uma matriz identidade de mesma dimensão da matriz original

In [ ]:
identidade = np.matmul(matriz, inversa_matriz)

In [ ]:
identidade

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00,
         0.00000000e+00,  1.38777878e-17,  1.38777878e-17],
       [-2.08166817e-17,  1.00000000e+00, -1.38777878e-17,
         0.00000000e+00,  0.00000000e+00, -2.77555756e-17],
       [-3.46944695e-18, -1.38777878e-17,  1.00000000e+00,
         0.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [-2.08166817e-17,  0.00000000e+00, -1.38777878e-17,
         1.00000000e+00,  5.55111512e-17, -1.38777878e-17],
       [ 2.42861287e-17, -1.38777878e-17,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.38777878e-17,  5.55111512e-17,  1.00000000e+00]])

Obervamos que alguns coeficientes da matriz que deveriam ser 0 ficaram com um número "resíduo" muito pequeno, por isso, construimos uma função que "varre" todos os elementos da matriz verificando se o elemento é um valor muito pequeno (no caso escolhemos 0.00000000001 ou 10^-11) e quando esse número é menor que o valor substituimos ele por 0

In [ ]:
def limpa_identidade(M):
  identidade_limpa = np.copy(M)
  n=len(M)
  i=0
  while i<n:
    j=0
    while j<n:
      if identidade_limpa[i,j]<0.00000000001:
        identidade_limpa[i,j] = 0
      j=j+1
    i=i+1
  return identidade_limpa


In [ ]:
id_limpa = limpa_identidade(identidade)

In [ ]:
id_limpa

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Desta forma, conseguimos observar com maior clareza que o resultado da multiplicação resulta em uma matriz identidade e alcançamos o objetivo de encontrar a matriz inversa

# Questão 2

Pela questão, formulamos as seguintes equações lineares:

1a + 1b + 1c = 12

1b + 2c = 10

2a + 1b + 1c = 16

Primeiro, pensamos em utilizar o método de Gauss-Seidel, mas percebemps que não poderia pelo fato de que o Teorema do Critério das Linhas não era satisfeito,o que também inviabilizou a utilização do método de Gauss-Jacobi. Assim, utilizamos o Método de Gauss-Jordan, obtendo:


In [ ]:
def gauss_jordan(A, b):
    ## n é a ordem da matriz A
    n = len(A)
    ## Para cada etapa k
    for k in range(0, n):

      ##Transformar o pivô em 1:
      for j in range(k+1,n):
        A[k][j] = A[k][j]/A[k][k]
      b[k]= b[k]/A[k][k]
      A[k][k] = 1

      ## Para cada linha i
      for i in range(0,n):
        if i != k:
          ## Calcula o fator m
          m = -A[i][k]/A[k][k]
          ## Atualiza a linha i da matriz, percorrendo todas as colunas j
          for j in range(k+1,n):
            A[i][j] = m*A[k][j] + A[i][j]
          # Atualiza o vetor b na linha i
          b[i] = m*b[k] + b[i]
          ## Zera o elemento Aik
          A[i][k] = 0

    return b

In [ ]:
A = [[1, 1, 1],
     [0, 1, 2],
     [2, 1, 1]]
b = [12, 10, 16]
x = gauss_jordan(A,b)
print(x)

[4.0, 6.0, 2.0]


Portanto, precisamos de 4 caminhões do tipo A, 6 caminhões do tipo B e 2 caminhões do tipo C.

# Questão 3

**Item a**

Pelas equações lineares:

i1 + i2 + i3 = 0

10i1 - 8i2 = 65

8i1 - 3i3 = 120

Pelo mesmo motivo da questão 2, utilizamos o método de Gauss-Jordan:

In [ ]:
B = [[1, 1, 1],
     [10, -8, 0],
     [8, 0, -3]]
c = [0, 65, 120]
y = gauss_jordan(B,c)
print(y)

[9.788135593220339, 4.110169491525424, -13.898305084745763]


Portanto, temos que i1 = 9.788135593220339, i2 = 4.110169491525424 e i3 = -13.898305084745763

**Item b**

Utilizamos o código a seguir:

In [ ]:
def determinante(A):
  # A é uma matriz quadrada 
  det = 0
  n = len(A)
  A = A.astype(np.float64) # Definindo o tipo dos dados como ponto flutuante, para ser possível operar sobre um vetor inteiro de uma só vez
  if n == 2:
    det = A[0][0]*A[1][1] - A[0][1]*A[1][0]
    # Fórmula para o cálculo do determinante de uma matriz quadrada de ordem 2
  else:
    for i in range(n):
      B = np.copy(A)
      B = np.delete(B, 0, 0)
      B = np.delete(B, i, 1)
      det += ((-1)**i)*A[0][i]*determinante(B)
      # Cálculo do determinante através do teorema de laplace recursivamente
  return det

Para calcular o determinante da matriz de coeficientes (B)

In [ ]:
B = np.array([[1, 1, 1],
     [10, -8, 0],
     [8, 0, -3]])
determinante(B)

118.0

Como o determinante deu diferente de 0, significa que a matriz B possui inversa

**Item c**

Utilizamos mesmo código da primeira questão para encontrar a matriz inversa de B

> Bloco com recuo



In [ ]:
#Input de dados da matriz
ordem=int(input('Ordem da Matriz: '))
matriz=np.zeros((ordem, ordem), dtype='float')
for i in range(ordem):
  for j in range(ordem):
    print('Coeficiente [', i+1, '][', j+1,']')
    c=float(input('Input: ' ))
    matriz[i,j] = c
print (matriz)

Ordem da Matriz: 3
Coeficiente [ 1 ][ 1 ]
Input: 1
Coeficiente [ 1 ][ 2 ]
Input: 1
Coeficiente [ 1 ][ 3 ]
Input: 1
Coeficiente [ 2 ][ 1 ]
Input: 10
Coeficiente [ 2 ][ 2 ]
Input: -8
Coeficiente [ 2 ][ 3 ]
Input: 0
Coeficiente [ 3 ][ 1 ]
Input: 8
Coeficiente [ 3 ][ 2 ]
Input: 0
Coeficiente [ 3 ][ 3 ]
Input: -3
[[ 1.  1.  1.]
 [10. -8.  0.]
 [ 8.  0. -3.]]


In [ ]:
inversa_B = gauss_jordan_inversa(matriz)

In [ ]:
inversa_B

array([[ 0.20338983,  0.02542373,  0.06779661],
       [ 0.25423729, -0.09322034,  0.08474576],
       [ 0.54237288,  0.06779661, -0.15254237]])

In [ ]:
identidade = np.matmul(matriz, inversa_B)

In [ ]:
identidade

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [-1.11022302e-16, -1.38777878e-17,  1.00000000e+00]])

In [ ]:
id_limpa = limpa_identidade(identidade)

In [ ]:
id_limpa

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Como foi possível comprovar, a matriz encontrada realmente corresponde à inversa de B

# Questão 4

Primeiramente, vamos verificar o cumprimento do critério de Sassenfeld

In [ ]:
def sassenfeld(A):
  A = A.astype(np.float64)
  A = abs(A)
  n = len(A)
  B = np.ones(n)
  for i in range(n):
    B[i] = (np.dot(A[i], B) - A[i][i]*B[i])/A[i][i]
  beta = max(B)
  if beta < 1:
    print('Critério cumprido')
  else:
    print('Critério não cumprido')

In [ ]:
A = np.array([[17,-2,-3],[-5,21,-2],[-5,-5,22]])
sassenfeld(A)

Critério cumprido


Uma vez que o critério foi cumprido, temos a garantia de que o método converge. Vamos agora definir o vetor B e utilizar o método de Gauss-Seidel para solucionar o sistema

In [ ]:
def gauss_seidel(A, B, erromax, maxiter=50, X=np.array([0,0]), iter=0):
  # A é a martiz de coeficientes do sistema, B um vetor com os termos independentes do sistema, erromax é o erro máximo tolerado, maxiter é o maior numero
  # de iterações permitido, X é o vetor solução atual e iter é o número de iterações realizadas
  A = A.astype(np.float64)
  B = B.astype(np.float64)
  # Definindo o tipo dos dados como ponto flutuante, para ser possível operar sobre um vetor inteiro de uma só vez
  n = len(A)
  if X.all() == 0:
    X = np.copy(B)
  X_antigo = np.copy(X)
  for i in range(n):
    X[i] = (-np.dot(A[i], X.T) + A[i][i]*X[i] + B[i])/A[i][i]
    # Calculando os novos valores de X, utilizando o vetor X já atualizado
  erro = max(abs(X_antigo - X))/max(abs(X)) # Calculando o erro obtido
  iter+=1
  if erro <= erromax or iter == maxiter:
    return X, iter # Retorna o vetor X que obteve erro tolerável ou foi obtido após o número máximo de iterações e o número de iterações realizadas
  return gauss_seidel(A, B, erromax, maxiter, X, iter) # Chama a própria função recursivamente caso os critérios de parada não tenham sido atingidos

In [ ]:
b = np.array([500,200,30])
x, iter = gauss_seidel(A, b, 0.0005, X=np.array([34,19,13]))
x, iter

(array([33, 18, 12]), 2)

Podemos perceber que o método encontrou tais valores extremamente rápido (com apenas duas iterações). Vamos calcular o resíduo obtido

In [ ]:
# Função para calcular o resíduo
def residuo(A, x, B):
  # A é a matriz de coeficientes do sistema, x é o vetor solução obtido por algum dos métodos e B é o vetor de termos independentes dos sistema
  return np.matmul(A, x) - B

In [ ]:
residuo(A, x, b)

array([-11, -11, -21])

Um resíduo extremamente alto! Isso ocorre devido à dois fatores: a aproximação inicial e o modo como o erro é calculado durante o método de Gauss Seidel. Para entendermos melhor isso, vamos utilizar um método direto (neste caso, o de Gauss) para encontrar uma solução mais precisa para o sistema

In [ ]:
def sol_triang_inf(A, B):
  # A é uma matriz triangular inferior e B um vetor com os termos independentes do sistema
  n = len(B)
  X = []
  for line in range(n):
    b = B[line]
    for column in range(line):
      b -= A[line][column]*X[column]
    x = b/A[line][line]
    # Obtemos os valores de X por substiruições recursivas
    X.append(x)
  return np.array(X)
  # Retornamos o vetor X

In [ ]:
# Função para transformar uma matriz triangular superior em uma triangular inferior
def inverte_matriz(A):
  # A é uma matriz triangular superior
  new_A = []
  for array in A[::-1]: # Inverte a ordem das linhas de A
    new_A.append(array[::-1]) # Inverte a ordem dos elementos de cada linha de A
  return np.array(new_A)

In [ ]:
def sol_triang_sup(A,B):
  # A é uma matriz triangular superior e B um vetor com os termos independentes do sistema
  A = inverte_matriz(A) # Transforma A em uma matriz triangular inferior
  B = B[::-1] # Inverte o vetor B
  return sol_triang_inf(A,B)[::-1] # Soluciona o sistema obtido e inverte os valores de X obtidos

In [ ]:
def gauss(A, b):
  # A é a matriz de coeficientes do sistema, b um vetor com os termos independentes do sistema, pivotar é uma variável que indica se deve ou não se utilizada
  # a estratégia de pivoteamento simples e returnL indica se devem ser retornadas as matrizes L e U para o método LU
  n = len(A)
  A = A.astype(np.float64) 
  b = b.astype(np.float64)
  # Definindo o tipo dos dados como ponto flutuante, para ser possível operar sobre um vetor inteiro de uma só vez
  B = np.copy(b) # Criando uma cópia do vetor B para não alterar o original
  for j in range(n-1): # Itera sobre as colunas de A, exceto a última
    for i in range(j+1,n): # Itera sobre as linhas de A a partir de j+1
      fator = A[i][j]/A[j][j]
      B[i] = B[i] - B[j]*fator # Onde B[i] e B[j] são reais
      A[i] = A[i] - A[j]*fator # Onde A[i] e A[j] são vetores
  return sol_triang_sup(A, B) # Retorna a solução do sistema se returnL = False

In [ ]:
x = gauss(A, b)
x

array([33.99631415, 18.89282676, 13.38389566])

In [ ]:
residuo(A, x, b)

array([0.00000000e+00, 2.84217094e-14, 0.00000000e+00])

Como podemos observar, obtemos valores com resíduos basicamente nulos dessa vez, mostrando que esses provavelmente são os resultados reais. Analisando mais profundamente, percebemos que os resultados obtidos são extremamente próximos à estimativa inicial fornecida ao método de Gauss Seidel, e é exatamente por isso que o resíduo obtido foi alto. O cálculo do erro pelo método de Gauss Seidel é realizado com base na diferença entre a estimativa atual e a anterior, o que faz sentido, tendo em vista que o método converge para um valor. Contudo, uma vez que fornecemos uma estimativa inicial próxima ao resultado desejado, a variação entre esta e a próxima será muito baixa, de modo que, mesmo que o resultado distancie do desejado, o erro será pequeno, fazendo com que o resíduo cresça

Para verificarmos isso mais claramente, vamos utilizar o método de Gauss Seidel, mas com nossa estimativa inicial padrão (x=B)

In [ ]:
x, iter = gauss_seidel(A, b, 0.0005)
x, iter

(array([33.99678773, 18.89306799, 13.38405812]), 6)

In [ ]:
residuo(A, x, b)

array([ 7.08106939e-03,  2.37285429e-03, -4.26325641e-14])

Como podemos perceber, o método iterou mais vezes e os resíduos obtidos foram extremamente menores (apesar de alguns ainda estarem superiores ao desejado)